name: redeploy Docker Image CI
on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: echo "REPOSITORY_NAME=$(echo 'volkerbaecker/w_spotdetection3d-ij-tophat')" >> $GITHUB_ENV
      shell: bash
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag  ${{ env.REPOSITORY_NAME }}:${{ steps.vars.outputs.tag }}
    - name: Push the tagged Docker image
      run: docker push ${{ env.REPOSITORY_NAME }}:${{ steps.vars.outputs.tag }}
