name: redeploy Docker Image CI
on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo "REPOSITORY_NAME=${{github.repository}}" >> $GITHUB_ENV
      shell: bash
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: show
      run: echo  ${{ env.REPOSITORY_NAME }}:${{ steps.vars.outputs.tag }}
    
