name: redeploy Docker Image CI
on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: get the username
      run: echo "USER_NAME=$(echo '${{ github.repository }}' | awk '{print tolower($0)}') | cut -d/ -f 1  | tr -d -" >> $GITHUB_ENV
      shell: bash
    - name: get the repository name
      run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk '{print tolower($0)}') |cut -d/ -f 2" >> $GITHUB_ENV
      shell: bash      
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: show
      run: echo  ${{ env.REPOSITORY_NAME }}/${{ env.REPOSITORY_NAME }}:${{ steps.vars.outputs.tag }}

    
